os: linux

language: c

addons:
    apt:
      update: true
      packages:
        - curl
        - python3
        - python3-pip
        - python3-pycurl

install:
    - cd $TRAVIS_BUILD_DIR/tools && git clone https://github.com/assinie/md2hlp.git
    - cd $TRAVIS_BUILD_DIR

script:
    - cd $TRAVIS_BUILD_DIR/tools
    - python3 retrieveSoftwareOricOrg.py
    - ls ../
    - ./builddocs.sh

after_success:
    - cd $TRAVIS_BUILD_DIR
    - VERSION=`cat VERSION`
    - cd orix && tar -zcvf ../softwares.tgz *
    - curl -X POST --data-binary '@softwares.tgz' "https://cdn.oric.org/publish.php?hash=$hash&path=/home/oricoujr/www/ftp/orix/dists/$VERSION/tgz/6502/softwares.tgz"
